name: rhuseinh
favicon: null
layout_spectrum: 0.4045533228199929
typography_spectrum: 0.9440211101900786
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7108112734276801
  lightness: 0.9867922882549465
  saturation: 0.9451190608087927
  rhythmicContrast: 0.6793470741249621
purpose: []
